language: python
python: 3.6.1
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov

script:
  -py.test --py.test --cov-report=term --cov=tests
after_success:coveralls
